"use strict";
/**
 * Lets the user log into YouTube inside a real Electron window (its own
 * persistent session, `persist:youtube-login`) and mirrors that session's
 * cookies out to cookies.txt in Netscape format - the same file
 * src/cookies.js already auto-detects for every yt-dlp call.
 *
 * Why a *separate* persistent partition instead of the app's default
 * session: keeps YouTube's auth cookies isolated from anything else the
 * app's own windows load, and - because Electron persists `persist:*`
 * session partitions to disk in userData automatically - the user only
 * has to log in ONCE. Every subsequent app launch just re-syncs
 * cookies.txt from the already-persisted session (see syncCookiesToFile()
 * called from main.js's app.whenReady()), no re-login needed until the
 * session actually expires/gets logged out.
 */
const { BrowserWindow, session } = require("electron");
const fs = require("fs");
// Reuse the exact same path src/cookies.js auto-detects, so a login here
// requires zero extra configuration on the yt-dlp side.
const { DEFAULT_COOKIES_FILE } = require("../src/cookies");

const PARTITION = "persist:youtube-login";
const LOGIN_URL = "https://accounts.google.com/ServiceLogin?service=youtube&continue=https%3A%2F%2Fwww.youtube.com%2F";

// Fallback expiry for session cookies (no expirationDate from Chromium) -
// yt-dlp's Netscape parser wants a real epoch, not "0 = end of session".
const FALLBACK_EXPIRY_DAYS = 180;

function toNetscapeLine(cookie) {
  const domain = cookie.domain || "";
  // Netscape's 2nd column means "applies to subdomains too" - true when the
  // cookie has a leading-dot domain (which is how Chromium reports
  // non-host-only cookies), false for exact-host-only cookies.
  const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
  const path = cookie.path || "/";
  const secure = cookie.secure ? "TRUE" : "FALSE";
  const expiry =
    typeof cookie.expirationDate === "number"
      ? Math.round(cookie.expirationDate)
      : Math.floor(Date.now() / 1000) + FALLBACK_EXPIRY_DAYS * 86400;
  return [domain, includeSubdomains, path, secure, expiry, cookie.name, cookie.value].join("\t");
}

/**
 * Pulls every cookie relevant to YouTube out of the login partition and
 * writes them to <BASE_DIR>/cookies.txt. Safe to call even if the user has
 * never logged in (just writes an empty-but-valid cookies file, which
 * src/cookies.js will pick up as "no useful cookies" - yt-dlp treats an
 * empty Netscape file the same as no cookies at all).
 */
async function syncCookiesToFile() {
  const ses = session.fromPartition(PARTITION);

  // get({url}) returns exactly what Chromium would send for a request to
  // that URL (domain-matching included); querying both hosts covers the
  // youtube.com session cookies AND the underlying google.com auth cookies
  // (SID/HSID/SAPISID/etc.) some yt-dlp code paths also check for.
  const [ytCookies, googleCookies] = await Promise.all([
    ses.cookies.get({ url: "https://www.youtube.com" }),
    ses.cookies.get({ url: "https://www.google.com" }),
  ]);

  const seen = new Set();
  const merged = [];
  for (const c of [...ytCookies, ...googleCookies]) {
    const key = `${c.domain}|${c.path}|${c.name}`;
    if (seen.has(key)) continue;
    seen.add(key);
    merged.push(c);
  }

  const lines = [
    "# Netscape HTTP Cookie File",
    "# Auto-generated by KanaeDesktop (desktop/youtubeCookies.js) - do not edit by hand.",
    ...merged.map(toNetscapeLine),
    "",
  ];

  fs.writeFileSync(DEFAULT_COOKIES_FILE, lines.join("\n"), "utf-8");

  console.log(`[YouTube Login] cookies.txt disinkron (${merged.length} cookie).`);
  return merged.length;
}

/**
 * Opens (or focuses, if already open) the YouTube login window. Syncs
 * cookies.txt as soon as the window is closed, regardless of whether the
 * login actually succeeded (a no-op sync if nothing changed).
 */
let _loginWin = null;

function openLoginWindow(parentWin, onStatus) {
  if (_loginWin && !_loginWin.isDestroyed()) {
    _loginWin.show();
    _loginWin.focus();
    return;
  }

  _loginWin = new BrowserWindow({
    width: 480,
    height: 680,
    parent: parentWin || undefined,
    modal: false,
    title: "Login ke YouTube",
    webPreferences: {
      partition: PARTITION,
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  });

  _loginWin.setMenuBarVisibility(false);
  _loginWin.loadURL(LOGIN_URL);

  _loginWin.on("closed", async () => {
    _loginWin = null;
    try {
      const count = await syncCookiesToFile();
      if (onStatus) onStatus({ ok: true, count });
    } catch (e) {
      console.error(`[YouTube Login] Gagal sinkron cookies: ${e.message}`);
      if (onStatus) onStatus({ ok: false, error: e.message });
    }
  });
}

module.exports = { openLoginWindow, syncCookiesToFile, PARTITION };
